
"use client";

import { useState, useEffect, useMemo, useRef } from 'react';
import type { Question } from '@/types';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardFooter,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Bookmark, Share, ThumbsUp, ThumbsDown, CheckCircle, Sparkles, Volume2, VolumeX, Loader2 } from 'lucide-react';
import React from 'react';
import { useSpeaker } from '@/hooks/use-speaker';

interface AnswerCardProps {
  question: Question;
  initialLang: 'en' | 'hi';
  isAiGenerated?: boolean;
}

// Simple markdown to HTML renderer
const renderMarkdown = (text: string) => {
    if (!text) return [];
    // Process bold first
    let processedText = text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    
    // Then split into paragraphs
    const paragraphs = processedText.split('\n').filter(p => p.trim() !== '');
  
    return paragraphs.map((para, i) => (
      <p key={i} className="mb-4 last:mb-0" dangerouslySetInnerHTML={{ __html: para }} />
    ));
  };


export function AnswerCard({ question, initialLang, isAiGenerated = false }: AnswerCardProps) {
  const [lang, setLang] = useState<'en' | 'hi'>(initialLang);
  const { isLoading: isSpeakerLoading, isPlaying, isMuted, toggleMute, speak, stop } = useSpeaker();
  const [playOnUnmute, setPlayOnUnmute] = useState(false);

  useEffect(() => {
    setLang(initialLang);
  }, [initialLang, question]);

  const textToSpeak = useMemo(() => {
    if (!question) return '';
    return [
      question[`question_${lang}`],
      'Short Answer.',
      question[`shortAnswer_${lang}`],
      'Key Takeaways.',
      ...(question[`summaryPoints_${lang}`] || []),
      'Detailed Explanation.',
      question[`longAnswer_${lang}`].replace(/\*\*(.*?)\*\*/g, '$1'),
    ]
      .join('. ')
      .trim();
  }, [question, lang]);

  const languageCode = lang === 'en' ? 'en-US' : 'hi-IN';

  // --- Speech Logic ---

  // This effect triggers playback *after* the state has been updated to un-muted.
  useEffect(() => {
    if (playOnUnmute && !isMuted) {
        speak(textToSpeak, languageCode);
        setPlayOnUnmute(false); // Reset the trigger
    }
  }, [playOnUnmute, isMuted, speak, textToSpeak, languageCode]);

  const handleSpeakerClick = () => {
    // If it's currently speaking, just stop it.
    if (isPlaying) {
        stop();
        return;
    }

    // If it's muted, unmute it and set a trigger to play on the next render.
    if (isMuted) {
        toggleMute();
        setPlayOnUnmute(true);
        return;
    }
    
    // If not playing and not muted, then play.
    speak(textToSpeak, languageCode);
  };

  // Stop speech when the component unmounts or question changes
  useEffect(() => {
    return () => {
      stop();
    };
  }, [stop, question]);


  const toggleLanguage = () => {
    setLang((prevLang) => (prevLang === 'en' ? 'hi' : 'en'));
  };

  const difficultyColors: { [key: string]: string } = {
    easy: 'bg-orange-100 text-orange-800 border-orange-200',
    medium: 'bg-orange-100 text-orange-800 border-orange-200', // Using same for medium
    hard: 'bg-red-100 text-red-800 border-red-200',
  };

  const categoryColors: { [key: string]: string } = {
    piping: 'bg-gray-100 text-gray-800 border-gray-200',
    welding: 'bg-gray-100 text-gray-800 border-gray-200',
    // Add other categories as needed
  };

  const getCategoryColor = (category?: string) => {
    if (typeof category === 'string') {
      return categoryColors[category.toLowerCase()] || 'bg-gray-100 text-gray-800 border-gray-200';
    }
    return 'bg-gray-100 text-gray-800 border-gray-200';
  };

  return (
    <Card className="w-full max-w-4xl mx-auto shadow-lg border-slate-200 mb-6 max-h-[80vh] flex flex-col">
      <CardHeader className="p-4 pb-3">
        <div className="flex flex-wrap items-center gap-2 mb-3">
          <Badge
            variant="outline"
            className={`uppercase text-[10px] font-bold ${difficultyColors[question.difficulty] || 'bg-gray-100 text-gray-800 border-gray-200'}`}
          >
            {question.difficulty}
          </Badge>
          <Badge 
            variant="outline"
            className={`text-[10px] font-bold ${getCategoryColor(question.category)}`}
          >
            {question.category || 'General'}
          </Badge>
           {isAiGenerated && (
            <Badge variant="outline" className="border-purple-500/30 bg-purple-500/10 text-purple-600 font-medium text-[10px]">
                <Sparkles className="mr-1.5 h-3 w-3" />
                Generated by AI
            </Badge>
           )}
        </div>
        <CardTitle className="font-bold text-base md:text-lg text-slate-800 mb-2">
          {question[`question_${lang}`]}
        </CardTitle>
        <div className="flex justify-between items-center">
          <Button variant="link" onClick={toggleLanguage} className="p-0 h-auto text-orange-600 font-semibold text-sm">
            {lang === 'en' ? 'Switch to Hinglish' : 'Switch to English'}
          </Button>
          <div className="flex items-center gap-0.5 text-slate-500">
             <Button variant="ghost" size="icon" className="h-8 w-8" onClick={handleSpeakerClick}>
                {isSpeakerLoading ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                ) : isMuted ? (
                    <VolumeX className="w-4 h-4" />
                ) : isPlaying ? (
                    <Volume2 className="w-4 h-4 text-primary animate-pulse" />
                ) : (
                    <Volume2 className="w-4 h-4 text-primary" />
                )}
            </Button>
            <Button variant="ghost" size="icon" className="h-8 w-8">
              <Bookmark className="w-4 h-4" />
            </Button>
            <Button variant="ghost" size="icon" className="h-8 w-8">
              <Share className="w-4 h-4" />
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4 p-4 pt-0 overflow-y-auto">
        <div>
          <h3 className="text-[11px] font-bold uppercase text-slate-500 mb-2">
            Quick Answer
          </h3>
          <p className="text-sm leading-relaxed text-slate-700">
            {question[`shortAnswer_${lang}`]}
          </p>
        </div>

        <div className="bg-green-50 p-3 rounded-lg border border-green-200">
          <h3 className="text-[11px] font-bold uppercase text-green-800 mb-2.5">
            Key Takeaways
          </h3>
          <ul className="space-y-1.5">
            {question[`summaryPoints_${lang}`] && question[`summaryPoints_${lang}`].map((point, index) => (
              <li key={index} className="flex items-start gap-2.5">
                <CheckCircle className="w-4 h-4 text-green-500 mt-0.5 shrink-0" />
                <span className="text-sm text-slate-800">{point}</span>
              </li>
            ))}
          </ul>
        </div>

        <Accordion type="single" collapsible defaultValue="item-1" className="w-full">
          <AccordionItem value="item-1" className="border-b-0">
            <AccordionTrigger className="text-[11px] font-bold uppercase text-slate-500 hover:no-underline py-2">
              Detailed Explanation
            </AccordionTrigger>
            <AccordionContent className="pt-2 text-slate-700 text-sm leading-relaxed">
                {renderMarkdown(question[`longAnswer_${lang}`])}
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </CardContent>
      <CardFooter className="flex flex-col items-start gap-2 pt-3 mt-auto border-t bg-slate-50/70 p-4">
         <p className="text-xs text-slate-600">Was this helpful?</p>
         <div className="flex gap-2">
            <Button variant="outline" size="sm" className="bg-white h-8 text-xs"><ThumbsUp className="mr-1.5 h-3.5 w-3.5"/> Yes</Button>
            <Button variant="outline" size="sm" className="bg-white h-8 text-xs"><ThumbsDown className="mr-1.5 h-3.5 w-3.5"/> No</Button>
         </div>
      </CardFooter>
    </Card>
  );
}
